name: pbdl
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  json_annotation: ^3.1.1
  hex: ^0.1.2
  quick_log: ^1.1.3
  http2: ^1.0.1
  path: ^1.8.0
  azblob: ^2.0.0
  recase: "^3.0.0"
  archive: ^3.1.2
  meta: 1.6.0
  uuid: ^3.0.4
  sentry: ^6.2.2

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.5.1
  pedantic: ^1.10.0
  test: ^1.16.0